spring:
  application:
    name: roaming-aggregator-service
  datasource:
    url: jdbc:h2:mem:roaming-aggregator-db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: false

springdoc:
  swagger-ui:
    path: /v1/swagger-ui
    show-common-extensions: true
    operations-sorter: alpha
    tags-sorter: alpha
    default-produces-media-type: application/json
    display-request-duration: true
    doc-expansion: none
    disable-swagger-default-url: true
